version: 0.2

phases:
  pre_build:
    commands:
      - echo "BUILD PAUSADO PARA DEBUG"
      - echo "Conecte via Session Manager agora"
      - echo "Voce tem 10 minutos para rodar migrations"
      - echo "Comandos cd tasks-app/backend && npm install && node migrations/create-tables.js"
      - sleep 600
      - echo "Build started on $(date)"
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo "Image tag - $IMAGE_TAG"

  build:
    commands:
      - echo "Building Docker image..."
      - cd tasks-app/backend
      - docker build -t $ECR_REPOSITORY_URI:latest .
      - docker tag $ECR_REPOSITORY_URI:latest $ECR_REPOSITORY_URI:$IMAGE_TAG
      - echo "Build completed on $(date)"

  post_build:
    commands:
      - echo "Pushing images to ECR..."
      - docker push $ECR_REPOSITORY_URI:latest
      - docker push $ECR_REPOSITORY_URI:$IMAGE_TAG
      - echo "Creating new task definition..."
      - sed "s|IMAGE_TAG|$IMAGE_TAG|g" aws/task-definition.json > /tmp/task-def.json
      - NEW_TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file:///tmp/task-def.json --region $AWS_DEFAULT_REGION --query 'taskDefinition.taskDefinitionArn' --output text)
      - echo "New task definition - $NEW_TASK_DEF_ARN"
      - echo "Updating ECS service..."
      - aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --task-definition $NEW_TASK_DEF_ARN --region $AWS_DEFAULT_REGION
      - cd ../..
      - printf '[{"name":"tasks","imageUri":"%s"}]' $ECR_REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo "Backend deployment completed!"

artifacts:
  files:
    - imagedefinitions.json

env:
  parameter-store:
    ECR_REPOSITORY_URI: /tasks-app/prod/ecr-repository-uri
    ECS_CLUSTER_NAME: /tasks-app/prod/ecs-cluster
    ECS_SERVICE_NAME: /tasks-app/prod/ecs-service
